services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t /var/www/public
    ports:
      - "8000:8000"

networks:
  default:
    driver: bridge
